export const siteContent = {
  brand: {
    name: 'Wesley Rodrigues',
    initials: 'WR',
    instagramLabel: '@wesleygestor01',
    instagramUrl: 'https://www.instagram.com/wesleygestor01',
  },
  links: {
    salesPage: 'https://pay.cakto.com.br/iywy9eh_1065545',
    terms: '#TERMOS-DE-USO',
    privacy: '#POLITICA-DE-PRIVACIDADE',
    contact: '#CONTATO',
  },
  hero: {
    eyebrow: 'Conheça a estratégia que mudou a minha trajetória',
    headlineStart: 'De porteiro a mais de',
    headlineHighlight: 'R$ 1 milhão',
    headlineEnd: 'faturado no digital.',
    subheadline: 'Eu vou te mostrar o modelo de produtos low ticket que utilizo para construir vendas pela internet — com oferta, processo e decisões baseadas em dados.',
    cta: 'Quero me inscrever',
  },
  lowTicketBenefits: [
    { title: 'Oferta simples', text: 'Uma proposta que o público consegue entender sem complicação.' },
    { title: 'Ticket acessível', text: 'Menor barreira inicial para a decisão de compra.' },
    { title: 'Processo estruturado', text: 'Etapas organizadas para sair da tentativa aleatória.' },
    { title: 'Possibilidade de escala', text: 'Uma estrutura que pode ser otimizada conforme os dados aparecem.' },
    { title: 'Venda pela internet', text: 'Uma operação digital preparada para encontrar e atender clientes.' },
    { title: 'Decisões com dados', text: 'Leitura do que acontece para evoluir oferta, página e aquisição.' },
  ],
  method: [
    { title: 'Produto', text: 'Uma solução clara para um problema específico.' },
    { title: 'Oferta', text: 'A forma de apresentar valor e facilitar a decisão.' },
    { title: 'Tráfego', text: 'O caminho para colocar a oferta diante das pessoas.' },
    { title: 'Conversão', text: 'A passagem do interesse para a compra.' },
    { title: 'Otimização', text: 'Melhorias orientadas pelo comportamento e pelos dados.' },
    { title: 'Escala', text: 'Expansão responsável do que já demonstra funcionar.' },
  ],
  audience: [
    'Você quer começar a vender produtos digitais.',
    'Já tentou o mercado digital, mas ficou perdido.',
    'Quer entender melhor a estrutura de low ticket.',
    'Busca um modelo de oferta mais simples.',
    'Já possui um produto, mas não vende com consistência.',
    'Quer compreender como estruturar uma operação digital.',
    'Quer aprender com alguém que utiliza o modelo no próprio negócio.',
  ],
  notFor: [
    'Procura dinheiro fácil.',
    'Não pretende aplicar o que aprender.',
    'Acredita em resultado sem execução.',
    'Espera retorno garantido.',
  ],
  modules: [
    { number: '01', title: 'Fundamentos do Low Ticket' },
    { number: '02', title: 'Escolha e estruturação da oferta' },
    { number: '03', title: 'Construção da página' },
    { number: '04', title: 'Aquisição de clientes' },
    { number: '05', title: 'Estrutura de vendas' },
    { number: '06', title: 'Análise e otimização' },
    { number: '07', title: 'Escala' },
  ],
  journey: {
    before: [
      'Não sabe qual produto vender.',
      'Não entende a estrutura.',
      'Testa estratégias aleatórias.',
      'Não sabe interpretar resultados.',
      'Depende de tentativa e erro.',
    ],
    after: [
      'Entende a lógica do low ticket.',
      'Consegue estruturar uma oferta.',
      'Conhece o caminho de aquisição.',
      'Entende o processo de conversão.',
      'Consegue tomar decisões utilizando dados.',
    ],
  },
  offer: {
    name: 'LOW TICKET NA PRÁTICA',
    price: '12x de R$ 35,00',
    payment: 'no cartão de crédito',
    items: [
      'Acesso ao treinamento',
      'Método passo a passo',
      'Estratégia de Low Ticket',
      '[BENEFÍCIO]',
      '[BENEFÍCIO]',
      '[BÔNUS]',
    ],
  },
  disclaimer: 'Os resultados apresentados nesta página referem-se à experiência e trajetória de Wesley Rodrigues. Resultados individuais variam de acordo com diversos fatores, incluindo execução, experiência, mercado e investimento. Não existe garantia de ganhos.',
} as const;

export type SiteContent = typeof siteContent;
